---
development:
  cloud_name: tranhaiquan2203
  api_key: '994852516885265'
  api_secret: DSHDf5N2LckU4GQRHqrbMUYTXpw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: tranhaiquan2203
  api_key: '994852516885265'
  api_secret: DSHDf5N2LckU4GQRHqrbMUYTXpw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: tranhaiquan2203
  api_key: '994852516885265'
  api_secret: DSHDf5N2LckU4GQRHqrbMUYTXpw
  enhance_image_tag: true
  static_image_support: false
