user:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 8
admins:
  per_page: 20
paginate:
  per_page: 10
  comment_pate: 5
image:
  width: 778
  height: 390
  widthbook: 500
  heightbook: 300
