user:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 8
  comment: 200
paginate:
  per_page: 6
  comment_page: 3
image:
  width: 778
  height: 390
  widthbook: 500
  heightbook: 300
